spring:
  application:
    name: familia-connect
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    queue-name: ${RABBITMQ_QUEUE}
    listener:
      binding-name: ${RABBITMQ_BINDING}
      exchange-name: ${RABBITMQ_EXCHANGE}
