spring:
  application:
    name: familia-connect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Mostra o SQL gerado no console (útil para desenvolvimento)
    show-sql: true
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    queue-name: ${RABBITMQ_QUEUE}
    listener:
      binding-name: ${RABBITMQ_BINDING}
      exchange-name: ${RABBITMQ_EXCHANGE}
